version: '2'
services:
    jhipsterblog-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/JHipsterBlog/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=JHipsterBlog
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
